// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile =  {
    "aws_project_region": "us-east-1",
    "aws_appsync_graphqlEndpoint": "https://r2zvn3vxujgaha37peoqbp53ze.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS",
    "aws_cognito_identity_pool_id": "us-east-1:2ed468a5-5b38-4190-aeed-38ac84084e8b",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_3ccvSNL4s",
    "aws_user_pools_web_client_id": "5ldmia0n6iu9mkoj3n8g3ogmte"
};


export default awsmobile;
